import {
  activities1,
  activities2,
  agricultural,
  avatar,
  biology,
  chemistry,
  computer,
  economics,
  geography,
  mathematics,
  nutrition,
  physics,
  teacherImg,
} from '@/app/assets';
import { ActivitiesAndEvent } from '@/type';

export const subjects = [
  {
    textbookImg: biology,
    subject: 'Biology',
    textbookName: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
  },
  {
    textbookImg: chemistry,
    subject: 'Chemistry',
    textbookName: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
  },
  {
    textbookImg: agricultural,
    subject: 'Agricultural Science',
    textbookName: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
  },
  {
    textbookImg: computer,
    subject: 'Computer',
    textbookName: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
  },
  {
    textbookImg: economics,
    subject: 'Economics',
    textbookName: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
  },
  {
    textbookImg: geography,
    subject: 'Geography',
    textbookName: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
  },
  {
    textbookImg: mathematics,
    subject: 'Mathematics',
    textbookName: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
  },
  {
    textbookImg: nutrition,
    subject: 'Nutrition',
    textbookName: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
  },
  {
    textbookImg: physics,
    subject: 'Physics',
    textbookName: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
  },
];

export const avatars = [
  {
    avater: avatar,
  },
  {
    avater: avatar,
  },
  {
    avater: avatar,
  },
  {
    avater: avatar,
  },
];

export const activitiesAndEvents: ActivitiesAndEvent = [
  {
    image: activities2,
    title: 'Jet club gathering',
    type: 'Event',
    mode: 'Physical',
    date: '16/03/202',
    category: 'For all students',
    price: 'FREE',
  },
  {
    image: activities1,
    title: 'End of the year party celebration',
    type: 'Event',
    mode: 'Physical',
    date: '16/03/202',
    category: 'For all students',
    price: 'N5,000',
  },
  {
    image: activities1,
    title: 'End of the year party celebration',
    type: 'Event',
    mode: 'Physical',
    date: '16/03/202',
    category: 'For all students',
    price: 'N5,000',
  },
  {
    image: activities1,
    title: 'End of the year party celebration',
    type: 'Event',
    mode: 'Physical',
    date: '16/03/202',
    category: 'For all students',
    price: 'N5,000',
  },
];

export const registeredActivitiesAndEvents: ActivitiesAndEvent = [
  {
    image: activities2,
    title: 'Jet club gathering',
    type: 'Event',
    mode: 'Physical',
    date: '16/03/202',
    category: 'For all students',
    price: 'FREE',
  },
  {
    image: activities1,
    title: 'End of the year party celebration',
    type: 'Event',
    mode: 'Physical',
    date: '16/03/202',
    category: 'For all students',
    price: 'N5,000',
  },
];
