import {
  activities1,
  activities2,
  agricultural,
  avatar,
  biology,
  chemistry,
  computer,
  economics,
  geography,
  mathematics,
  nutrition,
  physics,
  teacherImg,
  teacherImg2,
} from '@/app/assets';
import { ActivitiesAndEvent } from '@/app/lib/types';

export const subjectsList = [
  {
    id: 1,
    textbookImg: biology,
    subject: 'Biology',
    currentTopic: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
    students: [
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
    ],
  },
  {
    id: 2,
    textbookImg: chemistry,
    subject: 'Chemistry',
    currentTopic: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
    students: [
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
    ],
  },
  {
    id: 3,
    textbookImg: agricultural,
    subject: 'Agricultural Science',
    currentTopic: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
    students: [
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
    ],
  },
  {
    id: 4,
    textbookImg: computer,
    subject: 'Computer',
    currentTopic: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
    students: [
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
    ],
  },
  {
    id: 5,
    textbookImg: economics,
    subject: 'Economics',
    currentTopic: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
    students: [
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
    ],
  },
  {
    id: 6,
    textbookImg: geography,
    subject: 'Geography',
    currentTopic: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
    students: [
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
    ],
  },
  {
    id: 7,
    textbookImg: mathematics,
    subject: 'Mathematics',
    currentTopic: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
    students: [
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
    ],
  },
  {
    id: 8,
    textbookImg: nutrition,
    subject: 'Nutrition',
    currentTopic: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
    students: [
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
    ],
  },
  {
    id: 9,
    textbookImg: physics,
    subject: 'Physics',
    currentTopic: 'Teacher Professional Development and Student Outcomes',
    teacher: 'Esther Ezike',
    teacherImg: teacherImg,
    number_of_topics: '10',
    number_of_topics_covered: '4',
    students: [
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
      { name: 'Jamiu Yusuf', image: teacherImg2 },
    ],
  },
];
export const classes = [
  {
    id: 1,
    className: 'JSS 1A',
    teacherImg: teacherImg,
    teacher: 'Esther Ezike',
    number_of_male: 34,
    number_of_female: 43,
    number_of_student: 34 + 43,
  },
  {
    id: 2,
    className: 'JSS 1B',
    teacherImg: teacherImg,
    teacher: 'John Doe',
    number_of_male: 30,
    number_of_female: 40,
    number_of_student: 30 + 40,
  },
  {
    id: 3,
    className: 'JSS 1C',
    teacherImg: teacherImg,
    teacher: 'Jane Smith',
    number_of_male: 28,
    number_of_female: 35,
    number_of_student: 28 + 35,
  },
  {
    id: 4,
    className: 'JSS 2A',
    teacherImg: teacherImg,
    teacher: 'Michael Johnson',
    number_of_male: 32,
    number_of_female: 38,
    number_of_student: 32 + 38,
  },
  {
    id: 5,
    className: 'JSS 2B',
    teacherImg: teacherImg,
    teacher: 'Emily Davis',
    number_of_male: 29,
    number_of_female: 36,
    number_of_student: 29 + 36,
  },
  {
    id: 6,
    className: 'JSS 2C',
    teacherImg: teacherImg,
    teacher: 'David Wilson',
    number_of_male: 31,
    number_of_female: 37,
    number_of_student: 31 + 37,
  },
  {
    id: 7,
    className: 'JSS 3A',
    teacherImg: teacherImg,
    teacher: 'Sarah Brown',
    number_of_male: 33,
    number_of_female: 39,
    number_of_student: 33 + 39,
  },
  {
    id: 8,
    className: 'JSS 3B',
    teacherImg: teacherImg,
    teacher: 'James Taylor',
    number_of_male: 27,
    number_of_female: 34,
    number_of_student: 27 + 34,
  },
  {
    id: 9,
    className: 'JSS 3C',
    teacherImg: teacherImg,
    teacher: 'Patricia Anderson',
    number_of_male: 35,
    number_of_female: 42,
    number_of_student: 35 + 42,
  },
  {
    id: 10,
    className: 'SSS 1A',
    teacherImg: teacherImg,
    teacher: 'Robert Thomas',
    number_of_male: 36,
    number_of_female: 44,
    number_of_student: 36 + 44,
  },
  {
    id: 11,
    className: 'SSS 1B',
    teacherImg: teacherImg,
    teacher: 'Linda Martinez',
    number_of_male: 33,
    number_of_female: 41,
    number_of_student: 33 + 41,
  },
  {
    id: 12,
    className: 'SSS 1C',
    teacherImg: teacherImg,
    teacher: 'Christopher Garcia',
    number_of_male: 30,
    number_of_female: 39,
    number_of_student: 30 + 39,
  },
  {
    id: 13,
    className: 'SSS 2A',
    teacherImg: teacherImg,
    teacher: 'Barbara Rodriguez',
    number_of_male: 32,
    number_of_female: 40,
    number_of_student: 32 + 40,
  },
  {
    id: 14,
    className: 'SSS 2B',
    teacherImg: teacherImg,
    teacher: 'Paul Martinez',
    number_of_male: 31,
    number_of_female: 38,
    number_of_student: 31 + 38,
  },
  {
    id: 15,
    className: 'SSS 2C',
    teacherImg: teacherImg,
    teacher: 'Nancy Hernandez',
    number_of_male: 34,
    number_of_female: 42,
    number_of_student: 34 + 42,
  },
  {
    id: 16,
    className: 'SSS 3A',
    teacherImg: teacherImg,
    teacher: 'Kevin Lopez',
    number_of_male: 29,
    number_of_female: 37,
    number_of_student: 29 + 37,
  },
  {
    id: 17,
    className: 'SSS 3B',
    teacherImg: teacherImg,
    teacher: 'Karen Gonzalez',
    number_of_male: 28,
    number_of_female: 36,
    number_of_student: 28 + 36,
  },
  {
    id: 18,
    className: 'SSS 3C',
    teacherImg: teacherImg,
    teacher: 'Steven Harris',
    number_of_male: 33,
    number_of_female: 40,
    number_of_student: 33 + 40,
  },
  {
    id: 19,
    className: 'JSS 1D',
    teacherImg: teacherImg,
    teacher: 'Betty Clark',
    number_of_male: 31,
    number_of_female: 39,
    number_of_student: 31 + 39,
  },
  {
    id: 20,
    className: 'JSS 2D',
    teacherImg: teacherImg,
    teacher: 'Mark Lewis',
    number_of_male: 30,
    number_of_female: 38,
    number_of_student: 30 + 38,
  },
  {
    id: 21,
    className: 'JSS 3D',
    teacherImg: teacherImg,
    teacher: 'Sandra Walker',
    number_of_male: 32,
    number_of_female: 41,
    number_of_student: 32 + 41,
  },
  {
    id: 22,
    className: 'SSS 1D',
    teacherImg: teacherImg,
    teacher: 'Donald Hall',
    number_of_male: 29,
    number_of_female: 37,
    number_of_student: 29 + 37,
  },
  {
    id: 23,
    className: 'SSS 2D',
    teacherImg: teacherImg,
    teacher: 'Michelle Allen',
    number_of_male: 28,
    number_of_female: 36,
    number_of_student: 28 + 36,
  },
  {
    id: 24,
    className: 'SSS 3D',
    teacherImg: teacherImg,
    teacher: 'George Young',
    number_of_male: 33,
    number_of_female: 40,
    number_of_student: 33 + 40,
  },
  {
    id: 25,
    className: 'JSS 1E',
    teacherImg: teacherImg,
    teacher: 'Lisa King',
    number_of_male: 31,
    number_of_female: 39,
    number_of_student: 31 + 39,
  },
  {
    id: 26,
    className: 'JSS 2E',
    teacherImg: teacherImg,
    teacher: 'Brian Wright',
    number_of_male: 30,
    number_of_female: 38,
    number_of_student: 30 + 38,
  },
  {
    id: 27,
    className: 'JSS 3E',
    teacherImg: teacherImg,
    teacher: 'Dorothy Scott',
    number_of_male: 32,
    number_of_female: 41,
    number_of_student: 32 + 41,
  },
  {
    id: 28,
    className: 'SSS 1E',
    teacherImg: teacherImg,
    teacher: 'Jason Green',
    number_of_male: 29,
    number_of_female: 37,
    number_of_student: 29 + 37,
  },
  {
    id: 29,
    className: 'SSS 2E',
    teacherImg: teacherImg,
    teacher: 'Deborah Adams',
    number_of_male: 28,
    number_of_female: 36,
    number_of_student: 28 + 36,
  },
  {
    id: 30,
    className: 'SSS 3E',
    teacherImg: teacherImg,
    teacher: 'Charles Baker',
    number_of_male: 33,
    number_of_female: 40,
    number_of_student: 33 + 40,
  },
  {
    id: 31,
    className: 'JSS 1F',
    teacherImg: teacherImg,
    teacher: 'Jessica Nelson',
    number_of_male: 31,
    number_of_female: 39,
    number_of_student: 31 + 39,
  },
  {
    id: 32,
    className: 'JSS 2F',
    teacherImg: teacherImg,
    teacher: 'Matthew Carter',
    number_of_male: 30,
    number_of_female: 38,
    number_of_student: 30 + 38,
  },
  {
    id: 33,
    className: 'JSS 3F',
    teacherImg: teacherImg,
    teacher: 'Karen Mitchell',
    number_of_male: 32,
    number_of_female: 41,
    number_of_student: 32 + 41,
  },
  {
    id: 34,
    className: 'SSS 1F',
    teacherImg: teacherImg,
    teacher: 'Anthony Perez',
    number_of_male: 29,
    number_of_female: 37,
    number_of_student: 29 + 37,
  },
  {
    id: 35,
    className: 'SSS 2F',
    teacherImg: teacherImg,
    teacher: 'Sarah Roberts',
    number_of_male: 28,
    number_of_female: 36,
    number_of_student: 28 + 36,
  },
  {
    id: 36,
    className: 'SSS 3F',
    teacherImg: teacherImg,
    teacher: 'Daniel Turner',
    number_of_male: 33,
    number_of_female: 40,
    number_of_student: 33 + 40,
  },
  {
    id: 37,
    className: 'JSS 1G',
    teacherImg: teacherImg,
    teacher: 'Laura Phillips',
    number_of_male: 31,
    number_of_female: 39,
    number_of_student: 31 + 39,
  },
  {
    id: 38,
    className: 'JSS 2G',
    teacherImg: teacherImg,
    teacher: 'Thomas Campbell',
    number_of_male: 30,
    number_of_female: 38,
    number_of_student: 30 + 38,
  },
  {
    id: 39,
    className: 'JSS 3G',
    teacherImg: teacherImg,
    teacher: 'Betty Parker',
    number_of_male: 32,
    number_of_female: 41,
    number_of_student: 32 + 41,
  },
  {
    id: 40,
    className: 'SSS 1G',
    teacherImg: teacherImg,
    teacher: 'Edward Evans',
    number_of_male: 29,
    number_of_female: 37,
    number_of_student: 29 + 37,
  },
];

export const avatars = [
  {
    avater: avatar,
  },
  {
    avater: avatar,
  },
  {
    avater: avatar,
  },
  {
    avater: avatar,
  },
];

export const activitiesAndEvents: ActivitiesAndEvent = [
  {
    image: activities2,
    title: 'Jet club gathering',
    type: 'Event',
    mode: 'Physical',
    date: '16/03/202',
    category: 'For all students',
    price: 'FREE',
  },
  {
    image: activities1,
    title: 'End of the year party celebration',
    type: 'Event',
    mode: 'Physical',
    date: '16/03/202',
    category: 'For all students',
    price: 'N5,000',
  },
  {
    image: activities1,
    title: 'End of the year party celebration',
    type: 'Event',
    mode: 'Physical',
    date: '16/03/202',
    category: 'For all students',
    price: 'N5,000',
  },
  {
    image: activities1,
    title: 'End of the year party celebration',
    type: 'Event',
    mode: 'Physical',
    date: '16/03/202',
    category: 'For all students',
    price: 'N5,000',
  },
];

export const registeredActivitiesAndEvents: ActivitiesAndEvent = [
  {
    image: activities2,
    title: 'Jet club gathering',
    type: 'Event',
    mode: 'Physical',
    date: '16/03/202',
    category: 'For all students',
    price: 'FREE',
  },
  {
    image: activities1,
    title: 'End of the year party celebration',
    type: 'Event',
    mode: 'Physical',
    date: '16/03/202',
    category: 'For all students',
    price: 'N5,000',
  },
];
